ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# Install pip packages
RUN pip install openmim==0.3.9
RUN mim install mmengine
RUN mim install "mmcv>=2.0.0"
RUN mim install "mmdet>=3.0.0"
RUN mim install "mmdet3d>=1.1.0"